services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      APACHE_PORT: 11000
  nginx:
    build:
      context: ./nginx
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    environment:
      - SERVER_BASE_DOMAIN=${SERVER_BASE_DOMAIN}
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/files/dbms/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  nextclouddata: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
