services:
  nextcloud:
    build: ./nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/files/dbms/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  