services:
  nextcloudtest:
    build: ./nextcloud
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_TRUSTED_DOMAINS = nextcloud.belakkaf.net
      - OVERWRITECLIURL=https://nextcloud.belakkaf.net
      - OVERWRITEPROTOCOL=https
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/files/dbms/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
