services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      APACHE_PORT: 11000
  nginx:
    build:
      context: ./nginx
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    environment:
      - SERVER_BASE_DOMAIN=${SERVER_BASE_DOMAIN}
    networks:
        - monitoring
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/files/dbms/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  loki:
    container_name: loki
    volumes:
      - ./loki:/mnt/config
    ports:
      - 3100:3100
    image: grafana/loki:3.0.0
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
        - monitoring
  promtail:
    container_name: promtail
    volumes:
      - ./loki:/mnt/config
      - /var/lib/docker/volumes/master_data/_data/:/var/log
    links:
      - loki
    image: grafana/promtail:3.0.0
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN = grafana.local
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana
    networks:
      - monitoring
    depends_on:
      - loki
  rtmpStreaming:
    image: ghcr.io/grnd-alt/rtmp-new:main
    ports:
      - "1935:1935"
      - "8081:8080"
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
volumes:
  grafana:
  nextclouddata: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
