services:
  nextcloudtest:
    build: ./nextcloud
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_TRUSTED_DOMAINS = ${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITECLIURL=${OVERWRITECLIURL}
      - OVERWRITEPROTOCOL=https
      - NC_setup_create_db_user=false
  nginx:
    build:
      context: ./nginx
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    depends_on:
      - smarthome
      - request-counter
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    environment:
      - SERVER_BASE_DOMAIN=${SERVER_BASE_DOMAIN}
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/files/dbms/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db2:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - /share/request-count/dbms/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME_COUNTER}
      - POSTGRES_USER=${DB_USER_COUNTER}
      - POSTGRES_PASSWORD=${DB_PASSWORD_COUNTER}
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  smarthome:
    build: https://github.com/grnd-alt/smartHome.git
    volumes:
      - ./envfiles/smarthome.env:/.env
    ports:
      - 3000:3000
  request-counter:
    build: https://github.com/grnd-alt/request-counter.git#main:backend
    depends_on:
      - db2
    environment:
        - DB_USER=${DB_USER_COUNTER}
        - DB_PASSWORD=${DB_PASSWORD_COUNTER}
        - DB_NAME=${DB_NAME_COUNTER}
        - DB_URL=${DB_URL_COUNTER}
